### ISSUE TITLE
[Suggestion/request] Custom Circuits in Composite Hilbert Spaces

### ISSUE THREAD

**Issue by tibidabo** [scqubits/scqubits#190] opened 2023-05-30 14:51 UTC
Hello,
Thank you very much for the fantastic package. It is extraordinarily helpful. 

I would like to use the composite Hilbert Space feature with my qubit design implemented in the custom circuits feature. I intend to build semiclassical models of multiple custom qubits and interact with them using QuTiP. In my quick tests, I run into type errors.

Is it correct that this feature is not implemented? 
Is there a workaround, e.g. wrapping the custom circuits object into a compatible format? 
Do you plan to implement such compatibility?

I am a PhD student focusing on numerical cQED simulations and I am interested in contributing to a solution

Thank you very much,
Chris

**Comment by ZhaoTianPu** [comment] 2023-05-30 14:56
Hi Chris,

Thank you very much for your message. Could you please post a minimal working example snippet to show the failure? Thanks!

There are some ongoing developments on the HilbertSpace and Circuit module in `ZTP_qcspice` and/or `sec-noise` branches which are not yet going into the `main` branch. 

Best,
Tianpu

**Comment by tibidabo** [comment] 2023-05-30 15:47
## Minimal working example

```python
import scqubits as scq

# Weber parameters: Table I in Weber, Steven J., Gabriel O. Samach, David Hover, Simon Gustavsson, David K. Kim, Alexander Melville, Danna Rosenberg, et al. “Coherent Coupled Qubits for Quantum Annealing.” ArXiv:1701.06544 [Cond-Mat, Physics:Quant-Ph], June 6, 2017. https://doi.org/10.1103/PhysRevApplied.8.014004.

csfq4jj_yaml = """# CSFQ4JJ
branches:
- ["JJ", 1, 2, 102.31680319713882, 9.68511466232956]
- ["JJ", 2, 3, 102.31680319713882,  9.68511466232956]
- ["JJ", 3, 4, 102.31680319713882,  9.68511466232956]
- ["C", 1, 4, 0.36547602499356835]
- ["JJ", 1, 4, 38.741313831926355,  25.578636159485757]
"""

# load circuit design in scqubits
csfq4jj = scq.Circuit(csfq4jj_yaml, from_file=False, ext_basis="discretized")

# set external flux bias
csfq4jj.Φ1 = 0.5

resonator = scq.Oscillator(
    E_osc=4.5,
    truncated_dim=4
)

print(type(csfq4jj))
print(type(resonator))

hilbertspace = scq.HilbertSpace([csfq4jj, resonator])
print(hilbertspace)
```

### Describe the bug

I get the following error messages:

```python
(flux-qubit-theory) python 230530_CustomCircuit_CompositeHilbertSpace_example.py 
<class 'scqubits.core.circuit.Circuit'>
<class 'scqubits.core.oscillator.Oscillator'>
Traceback (most recent call last):
  File "230530_CustomCircuit_CompositeHilbertSpace_example.py", line 48, in <module>
    hilbertspace = scq.HilbertSpace([csfq4jj, resonator])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/scqubits/core/hilbert_space.py", line 377, in __init__
    self._evals_count = self.dimension
                        ^^^^^^^^^^^^^^
  File "python3.11/site-packages/scqubits/core/hilbert_space.py", line 547, in dimension
    return np.prod(np.asarray(self.subsystem_dims))  # type:ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in prod
  File "python3.11/site-packages/numpy/core/fromnumeric.py", line 3045, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

### Expected behaviour

I would like to input a custom circuit into a composite Hilbert space and interact with it using QuTiP.

### OS and version used:

- OS: macOS 13 (Apple M1)
- scqubits version 3.1.0
- Python version 3.11.0

**Comment by saipavanc** [comment] 2023-06-01 16:52
Since, we did not get a reply I will assume that the issue is resolved. I will close the issue now, feel free to open it if it did not get resolved.

**Closed by saipavanc** 2023-06-01 16:52 UTC
Labels: enhancement
