### ISSUE TITLE
Error in function `scqubits.HilbertSpace.generate_lookup()` when passing `evals_method` and `esys_method` keyword arguments

### ISSUE THREAD

**Issue by ofw24** [scqubits/scqubits#232] opened 2024-07-08 14:58 UTC
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x ] I have checked the API documentation.
 - [ x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
When creating an instance of `scqubits.HilbertSpace` and passing in keyword arguments `evals_method='evals_jax_dense'` and `esys_method='esys_jax_dense'`, the `HilbertSpace.generate_lookup()` function throws an error:

``` 
File "/Users/oliverwolff/anaconda3/envs/labcore/lib/python3.10/site-packages/scqubits/core/hilbert_space.py", line 627, in generate_lookup
    evals, evecs = self.eigensys(
  File "/Users/oliverwolff/anaconda3/envs/labcore/lib/python3.10/site-packages/scqubits/core/hilbert_space.py", line 762, in eigensys
    evals, evecs = diagonalizer(
  File "/Users/oliverwolff/anaconda3/envs/labcore/lib/python3.10/site-packages/scqubits/core/diag.py", line 689, in esys_jax_dense
    return evals[:evals_count], evecs[:, :evals_count]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

### Expected behavior
Expected to generate lookup table with attributes of the resonator and transmon.

### To Reproduce
To recreate the error:
```
self.hspace = scq.HilbertSpace(
            [resonator, transmon],
            evals_method='evals_jax_dense',
            esys_method='esys_jax_dense'
        )
self.hspace.generate_lookup()
```
where `resonator` and `transmon` are of type `scqubits.Oscillator` and `scqubits.Transmon`.

### OS and version used (please complete the following information):
 - OS: [MacOS 14.5 with M2 chip]
 - scqubits version [4.0.0]
 - Python version [3.10.13]

### Additional context
Any additional information you would like to provide to aid us.

**Comment by petergthatsme** [comment] 2024-07-08 15:46
Thanks for filing the report. 
First, could you please update to the latest released scqubits version (4.1) and double check that the issue is also present there?

**Comment by ofw24** [comment] 2024-07-08 18:53
I just upgraded to the newest version of scqubits and can confirm that I still have the same issue as before.

**Comment by petergthatsme** [comment] 2024-07-08 20:31
thanks for checking. Will take a look shortly.

**Comment by petergthatsme** [comment] 2024-07-16 03:49
This should be fixed now. The updates (along with numpy 2.0 compatibility) is in the `main` branch, if you want to give it a go... we will try to do a release in the next week or two (A few more issues still need to be sorted out). Also, just an fyi: you can also always provide a callable object (e.g function) to `esys_method` or `evals_method` where you can define yourself how the diagonalization is done or what lib is used. 
Thanks for reporting this. 

![image](https://github.com/user-attachments/assets/e16f935e-5c74-4eba-8187-907df6dd04d3)

**Comment by petergthatsme** [comment] 2024-07-16 04:00
I'll close this. Please reopen if the issue with `jax` persists (again, currently fix is in `main`).

**Closed by petergthatsme** 2024-07-16 04:00 UTC
