### ISSUE TITLE
[Bug report] Editing Noise Params with GUI

### ISSUE THREAD

**Issue by benmcdonough20** [scqubits/scqubits#173] opened 2022-12-13 05:06 UTC
### Documentation check
If the bug manifests in unexpected behavior (as opposed to a crash), confirm that you have consulted the 
[API documentation](https://scqubits.readthedocs.io/en/latest/api-doc/apidoc.html)

 - [x] I have checked the API documentation.
 - [x] I could not locate relevant information in the documentation or information is missing. 

### Describe the bug
In jupyter notebooks, editing any field in the Noise Params section of the scqubits GUI results in the following exception being raised: `local variable 'i_text_widget' referenced before assignment`

### Expected behavior
Expected behavior is to be able to edit the values of the textboxes in the Noise Params section of the scQubits GUI.

### To Reproduce
To reproduce this bug, call `scqubits.GUI()` in a jupyter notebook, navigate to the 'Noise Params' tab, and change the value of any of the text boxes by using the arrow keys or entering a new value and pressing 'Enter.'

### OS and version used:
 - OS: Manjaro Linux and Windows 10
 - scqubits version 3.1.0
 - Python version 3.10.6
 - jupyter version 6.5.2

### Additional context
@dkweiss31 informed me that he was unable to reproduce this bug on his system. The bug appeared in both my Linux and Windows setups, and I believe that he is using MacOS. This could point to the behavior being OS-dependent.

**Comment by jkochNU** [comment] 2022-12-13 15:35
@benmcdonough20 In what line number of gui.py is the exception raised?

I'm unable to reproduce this error on my machine (Windows 11). This is a problem none of the pytests would catch, however. It is possible there's a platform or version specific issue. Shoot me an email, please,  so we can look into this together.

@sujoju That variable is local to `coherence_text`. The nested `if`s there are hard to track...

**Comment by jkochNU** [comment] 2022-12-13 16:10
@benmcdonough20 This actually appears to be related to a fix pushed under #167. This has been incorporated into the current master, but has not been released yet. Can you please check out the current master (if you did not when running into this issue) and check whether the same problem occurs?

**Comment by benmcdonough20** [comment] 2022-12-13 16:24
@jkochNU My mistake! I didn't consider that the PyPi version would not be the most recent.

I cloned the master and the issue did not appear. Thanks!

**Comment by jkochNU** [comment] 2022-12-13 17:17
Closing this as addressed by fix to #167 & to be included in next incremental release.

**Closed by jkochNU** 2022-12-13 17:17 UTC
