### ISSUE TITLE
[Bug report] Flux Qubit Matrix Plotting

### ISSUE THREAD

**Issue by 99elam** [scqubits/scqubits#78] opened 2020-07-20 21:29 UTC
**Describe the bug**
The `.plot_matrixelements ` method shows incorrect coloring for the values when plotting the Hamiltonian of FluxQubit.

**Expected behavior**
When running `.plot_matrixelements('hamiltonian', mode='real')` the graph should look like a diagonal matrix. The values away from the diagonal are known to be zero, but the coloring (as specified by the legend) does not match this; the off diagonal elements are shown as non-zero.

**To Reproduce**
Create a `FluxQubit` object named `flux_qubit`, then call `flux_qubit.plot_matrixelements('hamiltonian', mode='real')`. The graph values look incorrect when compared to `flux_qubit.matrixelement_table('hamiltonian')`.

**OS and version used (please complete the following information):**
 - OS: Windows
 - scqubits version 1.2.3
 - Python version 3.7

**Additional context**
I'm not sure if this is a problem just for the Hamiltonian or just for the Flux qubit, but this is where I noticed the problem.

**Comment by jkochNU** [comment] 2020-07-20 21:36
![image](https://user-images.githubusercontent.com/19193849/87989034-f4e12880-caa6-11ea-8a92-152ddf94a509.png)

Confirmed - looks like the color legend is not being generated correctly. (In addition, it is obvious that matplotlib needs help with selecting a reasonable number of ticks on x and y axis.)

**Comment by jkochNU** [comment] 2020-07-20 22:16
This is fixed with https://github.com/scqubits/scqubits/commit/78c58eced5af582559267c043cb21ced90b77860 (color legend fix). 

(The tick marks issue is left untouched, as the typical use case are matrix elements for a few low-lying states. Can always override plot settings manually.)

**Closed by jkochNU** 2020-07-20 22:16 UTC
