### ISSUE TITLE
User-defined Diagonalization with cupy seem not to be optimised for parameters sweeps

### ISSUE THREAD

**Issue by tibidabo** [scqubits/scqubits#241] opened 2024-09-16 13:26 UTC
Dear scQubits team,

I am using the [user-defined diagonalization ](https://scqubits.readthedocs.io/en/v4.1/guide/settings/ipynb/custom_diagonalization.html#User-defined-Diagonalization)feature for a custom circuit which is relatively large. The cupy  (evals_cupy_dense) diagonalisation gives a modest to substantial speed up depending on the node charge cut-off.
But the GPU is much slower (20 times in my case) than the default CPU calculation in the [parameter sweep](https://scqubits.readthedocs.io/en/v4.1/guide/parametersweep/ipynb/paramsweep.html#Parameter-Sweeps:-single-qubit). Furthermore, the high performance GPU reaches the memory limit for much smaller node charge cut-off's than in the calculation without the sweep. Thus, the sweep method does not seem to be compatible with the user-defined diagonalization, at least in the cupy case.

Is the sweep feature already optimized for GPU usage?

Thank you very much.

**Comment by saipavanc** [comment] 2024-09-18 20:54
Thanks for raising the issue @tibidabo. Could you please also share an example where you are using this feature? It is possible that it is dependent on the qubit object with which you are initiating that method. It would be easier to check starting from an example. Thank you!

**Comment by tibidabo** [comment] 2024-09-25 12:08
Hello @saipavanc,
Thank you for your response. Sorry for not giving the example already. I had to modify my code to make it minimal and allow it to become public.

In the `evals_cupy_dense` case, you can see that the manual sweep is working, while for the same system and parameters, the scQubit sweep function is not.

In the `evals_cupy_sparse` both ways of sweeping are working.

Code
```
import time
import scqubits as sc
import numpy as np

def fqfq_circuit(circuit_parameters, evals_method="gpu"):
    """
    Creates two coupled flux qubits follwoing the circuit layout from the paper by Hita-Pérez et al.

    Returns:    

    References:
    Hita-Pérez, María, Gabriel Jaumà, Manuel Pino, and Juan José García-Ripoll.
    “Ultrastrong Capacitive Coupling of Flux Qubits.”
    August 5, 2021. http://arxiv.org/abs/2108.02549.
    """

    # layout of the circuit
    circuit =  f"""
    # fq-fq
        branches:
        - ["JJ", 0, 1, EJ={circuit_parameters['EJ']}, EC={circuit_parameters['EC']}]
        - ["JJ", 0, 2, EJ, EC]
        - ["JJ", 1, 2, EJalpha={circuit_parameters['alpha'] * circuit_parameters['EJ']}, ECalpha={circuit_parameters['alpha'] * circuit_parameters['EC']}]
        - ["C", 1,2, ECsh={circuit_parameters['beta'] * circuit_parameters['EC']}]
        - ["JJ", 2, 3, EJcoupling={circuit_parameters['EJc']}, ECcoupling={circuit_parameters['ECc'] + circuit_parameters['gamma'] * circuit_parameters['EC']}]
        - ["JJ", 3, 4, EJalpha, ECalpha]
        - ["C", 3, 4, ECsh]
        - ["JJ", 3, 0, EJ, EC]
        - ["JJ", 4, 0, EJ, EC]
    """

    # define circuit with corresponding eigensovler    
    if evals_method == "cpu":
        FQFQ = sc.Circuit(circuit, from_file=False)
    elif evals_method == "gpu":
        FQFQ = sc.Circuit(circuit, from_file=False, evals_method='evals_cupy_dense')
    else:
        raise ValueError("evals_method must be 'cpu' or 'gpu'")
    
    # set cutoff values
    FQFQ.cutoff_n_1=circuit_parameters['n_max_node']
    FQFQ.cutoff_n_2=circuit_parameters['n_max_node']
    FQFQ.cutoff_n_3=circuit_parameters['n_max_node']
    FQFQ.cutoff_n_4=circuit_parameters['n_max_node']       

    # set flux values
    FQFQ.Φ1 = circuit_parameters['phi_z_1']
    FQFQ.Φ2 = 0.0
    FQFQ.Φ3 = circuit_parameters['phi_z_2']
    
    return FQFQ

# Parameters
phi_z_1_array = np.linspace(0.4, 0.6, 51)
n_max_node_array = range(2, 16, 2)

circuit_parameters = {
    'phi_z_1': 0.5,
    'phi_z_2': 0.5,
    'EJ': 1.0,
    'EC': 1.0/35.0,
    'alpha': 0.5,
    'beta': 1.5,
    'EJc': 2.0,
    'ECc': 2.0/35.0,
    'gamma': 20.0,
    'n_max_node': 4 
}

# === Run basis size convergence vs computation time ===
print("=====================================================")
print("using sparse matrices in cupy: evals_cupy_dense")
print("=====================================================")
print("Basis size convergence vs computation time")
# GPU
for n in n_max_node_array:
    circuit_parameters['n_max_node'] = n
    try:
        t1 = time.time()
        FQFQ = fqfq_circuit(circuit_parameters, evals_method='gpu')
        _, _ = FQFQ.eigensys(5)
        t2 = time.time() - t1
        print(f"GPU: n = {n}, computation time = {t2} s")
    except Exception as e:
        print("Exception occurred, skipping this iteration: ", e)
        continue

# CPU
for n in n_max_node_array:
    circuit_parameters['n_max_node'] = n
    try:
        t1 = time.time()
        FQFQ = fqfq_circuit(circuit_parameters, evals_method='cpu')
        _, _ = FQFQ.eigensys(5)
        t2 = time.time() - t1
        print(f"CPU: n = {n}, computation time = {t2} s")
    except Exception as e:
        print("Exception occurred, skipping this iteration: ", e)
        continue


# === Run phi1 sweeps ===
# reset n_max_node, n_max_node did not converge for n_max_node=5, but any higher value crashes the GPU memory
circuit_parameters['n_max_node'] = 5

print("Phi1 sweep computation times")

# manual sweep
print("Phi1 manual sweep computation times")
# GPU
for phi in phi_z_1_array:
    circuit_parameters['phi_z_1'] = phi
    try:
        t1 = time.time()
        FQFQ = fqfq_circuit(circuit_parameters, evals_method='gpu')
        _, _ = FQFQ.eigensys(5)
        t2 = time.time() - t1
        print(f"manual sweep GPU: phi_z_1 = {phi}, computation time = {t2} s")
    except Exception as e:
        print("Exception occurred, skipping this iteration: ", e)
        continue

# CPU
for phi in phi_z_1_array:
    circuit_parameters['phi_z_1'] = phi
    try:
        t1 = time.time()
        FQFQ = fqfq_circuit(circuit_parameters, evals_method='cpu')
        _, _ = FQFQ.eigensys(5)
        t2 = time.time() - t1
        print(f"manual sweep CPU: phi_z_1 = {phi}, computation time = {t2} s")
    except Exception as e:
        print("Exception occurred, skipping this iteration: ", e)
        continue


# scQubits sweep
print("Phi1 scQubits sweep computation times")
# CPU
t1 = time.time()
FQFQ = fqfq_circuit(circuit_parameters, evals_method='cpu')
_ = FQFQ.get_spectrum_vs_paramvals(param_name='Φ1', param_vals=phi_z_1_array)
t2 = time.time() - t1
print("scQubits sweep CPU time:", t2)
#GPU
t1 = time.time()
FQFQ = fqfq_circuit(circuit_parameters, evals_method='gpu')
_ = FQFQ.get_spectrum_vs_paramvals(param_name='Φ1', param_vals=phi_z_1_array)
t2 = time.time() - t1
print("scQubits sweep GPU time:", t2)
```


Corresponding output dense
```
Basis size convergence vs computation time
GPU: n = 2, computation time = 0.4086587429046631 s
GPU: n = 4, computation time = 0.4161350727081299 s
GPU: n = 6, computation time = 1.1274359226226807 s
GPU: n = 8, computation time = 4.8204193115234375 s
GPU: n = 10, computation time = 17.18048357963562 s
GPU: n = 12, computation time = 41.91143274307251 s
GPU: n = 14, computation time = 103.32798075675964 s
CPU: n = 2, computation time = 0.23361706733703613 s
CPU: n = 4, computation time = 0.36736536026000977 s
CPU: n = 6, computation time = 1.1129093170166016 s
CPU: n = 8, computation time = 4.796673774719238 s
CPU: n = 10, computation time = 17.070943593978882 s
CPU: n = 12, computation time = 42.82362771034241 s
CPU: n = 14, computation time = 104.37700963020325 s
Phi1 sweep computation times
Phi1 manual sweep computation times
manual sweep GPU: phi_z_1 = 0.4, computation time = 0.5066177845001221 s
...
manual sweep GPU: phi_z_1 = 0.6, computation time = 0.5753803253173828 s
manual sweep CPU: phi_z_1 = 0.4, computation time = 0.5251548290252686 s
...
manual sweep CPU: phi_z_1 = 0.6, computation time = 0.525104284286499 s
Phi1 scQubits sweep computation times
scQubits sweep CPU time: 20.81020188331604
Traceback (most recent call last):
  File "/home/cqed-code-base/ChrisH-FQ-C-FQ-benchmarking/fqfq_sharewithscqubitsteam.py", line 152, in <module>
    _ = FQFQ.get_spectrum_vs_paramvals(param_name='Φ1', param_vals=phi_z_1_array)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/cqed/lib/python3.11/site-packages/scqubits/core/qubit_base.py", line 645, in get_spectrum_vs_paramvals
    list(
  File "/home/miniconda3/envs/cqed/lib/python3.11/site-packages/scqubits/core/qubit_base.py", line 594, in _evals_for_paramval
    return self.eigenvals(evals_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/cqed/lib/python3.11/site-packages/scqubits/core/qubit_base.py", line 369, in eigenvals
    evals = diagonalizer(self.hamiltonian(), evals_count, **options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/cqed/lib/python3.11/site-packages/scqubits/core/diag.py", line 459, in evals_cupy_dense
    evals_gpu = cp.linalg.eigvalsh(cp.asarray(m), **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/cqed/lib/python3.11/site-packages/cupy/linalg/_eigenvalue.py", line 185, in eigvalsh
    return _syevd(a, UPLO, False)[0]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/cqed/lib/python3.11/site-packages/cupy/linalg/_eigenvalue.py", line 51, in _syevd
    work_device = cupy.empty(work_device_size, 'b')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/cqed/lib/python3.11/site-packages/cupy/_creation/basic.py", line 31, in empty
    return cupy.ndarray(shape, dtype, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 137, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 225, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1445, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1137, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1382, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1385, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 10,319,711,232 bytes (allocated so far: 17,179,314,176 bytes).
```

Output sparse
```
Basis size convergence vs computation time
GPU: n = 2, computation time = 0.5616772174835205 s
GPU: n = 4, computation time = 0.41182899475097656 s
GPU: n = 6, computation time = 1.136587142944336 s
GPU: n = 8, computation time = 4.826003313064575 s
GPU: n = 10, computation time = 17.03957200050354 s
GPU: n = 12, computation time = 43.04829287528992 s
GPU: n = 14, computation time = 104.56217908859253 s
CPU: n = 2, computation time = 0.23589229583740234 s
CPU: n = 4, computation time = 0.36880040168762207 s
CPU: n = 6, computation time = 1.1061780452728271 s
CPU: n = 8, computation time = 5.1450583934783936 s
CPU: n = 10, computation time = 16.996985912322998 s
CPU: n = 12, computation time = 43.214553117752075 s
CPU: n = 14, computation time = 104.57039093971252 s
Phi1 sweep computation times
Phi1 manual sweep computation times
manual sweep GPU: phi_z_1 = 0.4, computation time = 0.5255205631256104 s
...
manual sweep GPU: phi_z_1 = 0.6, computation time = 0.5708847045898438 s
...
manual sweep CPU: phi_z_1 = 0.6, computation time = 0.5353438854217529 s
Phi1 scQubits sweep computation times
scQubits sweep CPU time: 21.408584594726562
scQubits sweep GPU time: 11.854235172271729
```

**Comment by petergthatsme** [comment] 2024-10-06 16:10
Thanks for reaching out @tibidabo.
First, there is a typo in your code. The problem is that you set: 
`FQFQ = sc.Circuit(circuit, from_file=False, evals_method='evals_cupy_dense')`
but then later on, do:
`_, _ = FQFQ.eigensys(5)`
This last command finds the eigensystem (both evals and evecs), where as in the first line you told scqubits to use the GPU when calculating eigenvalues only. 
The right way would have been to set:
`FQFQ = sc.Circuit(circuit, from_file=False, esys_method='esys_cupy_dense')`
When you do that you will actually be using your GPU to find the spectrum (and treat the Hamiltonian as a dense matrix). 
This will fail in your example on most GPUs because indeed the matrices get big very quickly... and you just run out of memory. This has little to do with "optimization".. it's just the nature of the beast - you are limited by the memory of the cards you're using. 
One way forward though, is to use GPU's sparse diagonalization. You can do that by setting: 
`FQFQ = sc.Circuit(circuit, from_file=False, esys_method='esys_cupy_sparse')`
On my particular hardware, this leads to a >2x speedup over (default) CPU method for some of the larger systems you're looking at:
```
Basis size convergence vs computation time
GPU: n = 2, computation time = 0.2627449035644531 s
GPU: n = 4, computation time = 0.6131401062011719 s
GPU: n = 6, computation time = 0.34154582023620605 s
GPU: n = 8, computation time = 1.0722644329071045 s
GPU: n = 10, computation time = 3.8008294105529785 s
GPU: n = 12, computation time = 11.047780275344849 s
GPU: n = 14, computation time = 28.08868908882141 s
CPU: n = 2, computation time = 0.12694978713989258 s
CPU: n = 4, computation time = 0.208543062210083 s
CPU: n = 6, computation time = 0.6547250747680664 s
CPU: n = 8, computation time = 3.508267402648926 s
CPU: n = 10, computation time = 15.868654251098633 s
CPU: n = 12, computation time = 30.783515453338623 s
CPU: n = 14, computation time = 75.92642951011658 s
```
Having said all this, there are some difference in how things are done... the GPU code at the moment does not check if you have degeneracies; something i want to implement, whereas the CPU default method does. Also note, that you can easily play with things/settings/methods yourself, as you can actually pass your own diagonalization methods with whatever settings you choose. Take a look at: https://scqubits.readthedocs.io/en/v3.3/guide/settings/ipynb/custom_diagonalization.html#Custom-procedures
You can utilize the stuff we've already written to get started - see here: 
https://github.com/scqubits/scqubits/blob/main/scqubits/core/diag.py

I will close this for now, but let me know if you have other questions or find problems. Thanks.

**Closed by petergthatsme** 2024-10-06 16:10 UTC
Labels: enhancement
